const app = document.querySelector('#app');
const toast = document.querySelector('#toast');
let items = [];
let admin = false;

async function request(url, options = {}) {
  const response = await fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Something went wrong.');
  return data;
}
async function loadItems() { items = await request('/api/items'); return items; }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[char]); }
function itemCard(item) { return `<a class="item-card" href="#detail/${encodeURIComponent(item.id)}"><div class="item-image" aria-hidden="true">${item.image ? `<img src="${item.image}" alt="">` : '✳'}</div><div class="item-info"><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.location)}</p><p>${escapeHtml(item.date)}</p></div><span class="tag">${escapeHtml(item.status)}</span></div></a>`; }
function layout(content) { app.innerHTML = `<div class="page">${content}</div>`; updateActiveNav(); window.scrollTo(0, 0); }
function updateActiveNav() { const page = location.hash.slice(1).split('/')[0] || 'home'; document.querySelectorAll('[data-page]').forEach(link => link.classList.toggle('active', link.dataset.page === page)); }

async function home() { await loadItems(); layout(`<section class="hero"><div><div class="eyebrow">01 / a smarter campus noticeboard</div><h1 class="display">lost things<br>find <em>people.</em></h1><p class="lede">Khoj Khabar brings your campus together to return the things that matter, one honest notice at a time.</p><a class="button" href="#board">Explore the board <span>↗</span></a></div><div class="hero-art"><div class="hero-sticker">MISSING<br>NO MORE<br>✳</div><div class="phone"><div class="phone-screen"><div class="phone-top">KHOJ / KHABAR</div><div class="phone-title">it's<br>been found.</div><div class="phone-photo"></div><div class="phone-line">Your next notice<br><b>could help someone.</b></div></div></div></div></section><section><div class="section-head"><h2>Fresh on the board</h2><a class="text-link" href="#board">See all notices ↗</a></div><div class="cards">${items.length ? items.slice(0, 3).map(itemCard).join('') : '<div class="empty">No notices yet. Be the first to post one.</div>'}</div></section><section class="cta-band"><h2>Found something?<br>Leave a little note.</h2><a class="button light" href="#report">Post a notice <span>↗</span></a></section>`); }
async function board() { await loadItems(); layout(`<div class="page-intro"><div><div class="eyebrow">02 / community board</div><h1>the board<br>is <em>alive.</em></h1></div><div class="board-tools"><input id="search" type="search" placeholder="Search notices..." aria-label="Search notices"><select id="status-filter" aria-label="Filter notices"><option value="all">All notices</option><option value="Found">Found</option><option value="Looking for">Looking for</option></select></div></div><div id="board-grid" class="board-grid"></div>`); renderBoard(); document.querySelector('#search').addEventListener('input', renderBoard); document.querySelector('#status-filter').addEventListener('change', renderBoard); }
function renderBoard() { const query = document.querySelector('#search').value.toLowerCase(); const status = document.querySelector('#status-filter').value; const filtered = items.filter(item => (status === 'all' || item.status === status) && `${item.title} ${item.location}`.toLowerCase().includes(query)); document.querySelector('#board-grid').innerHTML = filtered.length ? filtered.map(itemCard).join('') : '<div class="empty">No notices match that search yet.</div>'; }
async function detail(id) { const item = await request(`/api/items/${encodeURIComponent(id)}`); layout(`<div class="detail-layout"><div><a class="back-link" href="#board">← Back to board</a><div class="detail-image">${item.image ? `<img src="${item.image}" alt="${escapeHtml(item.title)}">` : '<span>✳</span>'}</div></div><div class="detail-copy"><div class="eyebrow">notice / ${escapeHtml(item.status)}</div><h1>${escapeHtml(item.title)}</h1><div class="detail-meta"><div><span>WHERE</span><strong>${escapeHtml(item.location)}</strong></div><div><span>WHEN</span><strong>${escapeHtml(item.date)}</strong></div></div><div class="detail-description"><span>DETAILS</span><p>${escapeHtml(item.details || 'No extra details were added to this notice.')}</p></div><a class="button" href="#report">Post another notice <span>↗</span></a></div></div>`); }
async function report() { layout(`<div class="form-layout"><div><div class="eyebrow">03 / add to the board</div><h1>make it<br><em>known.</em></h1><p class="notice">A clear photo and a tiny bit of context can turn a missing object into a reunion. Please do not share sensitive personal information.</p></div><form class="report-form" id="report-form"><div class="form-grid"><div class="form-field full"><label for="item-image">Photo of the item</label><div class="upload-box" id="upload-box"><input id="item-image" type="file" accept="image/*"><div class="upload-content"><b>+</b>Drop a photo here or browse<br><small>JPG, PNG · 5 MB max</small></div><img class="preview" alt="Selected item preview"></div></div><div class="form-field"><label for="title">What is it?</label><input id="title" required placeholder="e.g. Blue water bottle"></div><div class="form-field"><label for="status">Notice type</label><select id="status"><option>Found</option><option>Looking for</option></select></div><div class="form-field"><label for="location">Where?</label><input id="location" required placeholder="e.g. Library, 2nd floor"></div><div class="form-field"><label for="date">When?</label><input id="date" required placeholder="e.g. Today, 10:30 AM"></div><div class="form-field full"><label for="details">A few details</label><textarea id="details" placeholder="Colour, brand, identifying details..."></textarea></div></div><div class="form-actions"><span class="required">* Required fields</span><button class="button" type="submit">Publish notice <span>↗</span></button></div></form></div>`); let imageData = ''; document.querySelector('#item-image').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { imageData = reader.result; document.querySelector('.preview').src = imageData; document.querySelector('#upload-box').classList.add('has-image'); }; reader.readAsDataURL(file); }); document.querySelector('#report-form').addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/items', { method: 'POST', body: JSON.stringify({ title: document.querySelector('#title').value, status: document.querySelector('#status').value, location: document.querySelector('#location').value, date: document.querySelector('#date').value, details: document.querySelector('#details').value, image: imageData }) }); showToast('Your notice is now on the board.'); location.hash = 'board'; } catch (error) { showToast(error.message); } }); }
async function adminPage() { if (!admin) { layout(`<div class="admin-layout"><div class="eyebrow">05 / moderation</div><h1>admin<br><em>access.</em></h1><form class="admin-panel login-form" id="login-form"><h2>Sign in to manage notices</h2><div class="form-field"><label for="admin-user">Username</label><input id="admin-user" required autocomplete="username"></div><div class="form-field"><label for="admin-password">Password</label><input id="admin-password" type="password" required autocomplete="current-password"></div><button class="button" type="submit">Log in <span>↗</span></button><p class="admin-message" id="login-message"></p></form></div>`); document.querySelector('#login-form').addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/admin/login', { method: 'POST', body: JSON.stringify({ username: document.querySelector('#admin-user').value, password: document.querySelector('#admin-password').value }) }); admin = true; await adminPage(); } catch (error) { document.querySelector('#login-message').textContent = error.message; } }); return; } await loadItems(); layout(`<div class="admin-layout"><div class="eyebrow">05 / moderation</div><h1>keep it<br><em>tidy.</em></h1><div class="admin-panel"><h2>Notice moderation</h2><div class="admin-list">${items.length ? items.map(item => `<div class="admin-row"><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.location)} · ${escapeHtml(item.status)}</p></div><div class="admin-actions">${item.status !== 'Found' ? `<button data-action="found" data-id="${item.id}">Mark found</button>` : ''}<button class="danger" data-action="delete" data-id="${item.id}">Remove</button></div></div>`).join('') : '<div class="empty">There are no notices to moderate.</div>'}</div></div></div>`); document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', async () => { try { await request(`/api/admin/items/${button.dataset.id}`, { method: button.dataset.action === 'delete' ? 'DELETE' : 'PATCH', body: JSON.stringify({ status: 'Found' }) }); showToast(button.dataset.action === 'delete' ? 'Notice removed.' : 'Notice marked as found.'); await adminPage(); } catch (error) { showToast(error.message); } })); }
async function about() { layout(`<div class="about-grid"><div><div class="eyebrow">04 / why khoj khabar</div><h1>good<br>things<br><em>come<br>back.</em></h1></div><div class="about-copy"><p>Campus is a small city. We pass the same corridors, sit on the same steps, and sometimes leave our favourite things behind.</p><p>Khoj Khabar is a simple, student-built way to make those near-misses less permanent: a living board for lost objects, found objects, and the people looking for them.</p><div class="principles"><div class="principle"><strong>01 / local</strong><p>Every notice belongs to this campus community.</p></div><div class="principle"><strong>02 / clear</strong><p>Good details make a good return possible.</p></div><div class="principle"><strong>03 / kind</strong><p>We leave out sensitive details and keep it human.</p></div><div class="principle"><strong>04 / open</strong><p>Anyone can help close the loop.</p></div></div></div></div>`); }
async function route() { const [page, id] = location.hash.slice(1).split('/'); try { if (page === 'detail' && id) return await detail(id); if (page === 'admin') return await adminPage(); return await ({ home, board, report, about }[page] || home)(); } catch (error) { layout(`<div class="empty">${escapeHtml(error.message)}</div>`); } }
+window.addEventListener('hashchange', route); route();
